### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by pratiweb** [WordPress/Learn#808] opened 2022-07-07 05:01 UTC
There is design issue in pagination links and submit an idea button

https://learn.wordpress.org/course-category/contributing-to-wordpress/

https://i.imgur.com/Zn9NqJY.jpg

**Comment by vagelisp** [comment] 2022-07-12 11:27
That's a duplicate of #797

**Comment by hlashbrooke** [comment] 2022-07-13 03:46
Closing as this is a duplicate.

**Closed as completed by hlashbrooke** 2022-07-13 03:46 UTC
