### ISSUE TITLE
Learn WordPress Content Error Report - 130356

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#1310] opened 2023-02-06 03:44 UTC
# Error Description
- Content URL: https://learn.wordpress.org/learn/quiz/a-hands-on-experiment-with-the-block-editor/

Questions 3 and 4 seem to refer to images but they do not display during the quiz.

# Error Report Checklist:
- [x] Error Validated
- [ ] Error fix proposed
- [ ] Error fix reviewed
- [ ] Error fix published

**Comment by kaitohm** [comment] 2023-05-12 09:11
Duplicate of #826

**Closed as completed by kaitohm** 2023-05-12 09:11 UTC
Labels: Awaiting Triage, [Content] Feedback
