### ISSUE TITLE
Add license information for the contents

### ISSUE THREAD

**Issue by naokomc** [WordPress/Learn#120] opened 2020-09-17 03:56 UTC
It will be helpful to explicitly mention the license of the contents on the learn.wordpress.org site so that meetup organizers and others can make use of the resources with that knowledge.

The GitHub repository for the lesson plan contents has a [license file (GPL3)](https://github.com/wptrainingteam/block-directory/blob/master/LICENSE).
[WordPress.tv](https://wordpress.tv/) shows CC BY-SA 4.0 license on the home page and individual video pages. I like this method because it's very clear.

How about showing WordPress.tv-style license information to each piece of content (on the sidebar)?

![image](https://user-images.githubusercontent.com/34067/93418333-23338680-f8e5-11ea-91e0-e3f48c438645.png)

**Comment by hlashbrooke** [comment] 2020-09-28 14:19
I agree with this - since the video content is hosted on wptv, we can use the same licence they use.

**Comment by courtneyr-dev** [comment] 2020-12-15 11:39
Without researching too far at this moment, I think an appropriate variety on the sidebar for lesson plans is appropriate as well.

**Comment by varlese** [comment] 2021-03-15 17:09
Since all of the content on the site uses the same licensing, and we're building out the Learn WordPress Handbook, are there any downsides to placing this info in the [What is Learn WordPress](https://learn.wordpress.org/handbook/) section rather than in the side bar?

**Comment by naokomc** [comment] 2021-03-17 07:42
As long as it's easy to find, I personally think totally fine to have it somewhere that's not on the sidebar. Adding it to a static page requires not coding, so we should go ahead and add to clarify the information.

Footer is another common place to put document license info.

Mozilla MDN
![image](https://user-images.githubusercontent.com/34067/111248101-94fa4c00-864c-11eb-94de-fd4bbf73b3c5.png)

Wikipedia
![image](https://user-images.githubusercontent.com/34067/111248268-ed314e00-864c-11eb-9f52-21bc3e53bf48.png)

**Comment by varlese** [comment] 2021-03-19 12:35
Hm, in terms of visibility, I agree that the footer is better! Still thinking of no/low-code solutions, what do you think of creating a re-usable "Licensing" block in the interim? In workshops, the person reviewing could just manually add before publishing the workshop and the result would look something like this:
<img width="980" alt="Screen Shot 2021-03-19 at 08 30 22" src="https://user-images.githubusercontent.com/1361760/111780409-bbf39080-888d-11eb-8862-d41da1503970.png">

If it's not too hard to incorporate into the blocks that are automatically populated into the Workshop post type, we can always add that automatically down the line.

For lesson plans, perhaps that same reusable block could be added to the bottom/footer of the current Lesson Plan Template. (@courane01 would love your thoughts on this option for the Training team workflow!)

**Comment by coreymckrill** [comment] 2021-03-19 23:43
I think that column in the workshops is actually going to become part of the static template, outside of the post content (see #200). So as long as we're thinking we would use the same license on every workshop, it should be simple to add it to the static sidebar template as well.

**Comment by hlashbrooke** [comment] 2021-08-11 23:58
Revisiting this so we can make some headway.

Yes, let's add the licencing info to the workshop and lesson plans sidebar as @varlese showed in the mockup. It can be the same static content for both post types, but the strings will need to be available for localisation.

**Comment by hlashbrooke** [comment] 2021-08-25 01:34
I discussed this with @josephahaden - she has confirmed that we can use the CC BY-SA 4.0 licence for all content on Learn WordPress, so please let's move forward with adding the licence details to the site. This will also require a post on Make/Training about the decision, but that can come when the dev work is done here.

**Comment by hlashbrooke** [comment] 2021-11-14 08:04
With #239 adding new sidebar widget areas for each post type, this licence information has now been added to those widget areas and can be edited from the dashboard. Closing this issue.

**Closed as completed by hlashbrooke** 2021-11-14 08:04 UTC
Labels: [Type] Enhancement, [Type] Good First Issue, [Component] Learn Theme, Priority - High, [Component] Content
