### ISSUE TITLE
Gujarati translation for Handbook Page "Tutorials"

### ISSUE THREAD

**Issue by SagarLadani** [WordPress/Learn#1234] opened 2023-01-09 06:32 UTC
# Details
- Link to original content: [https://make.wordpress.org/training/handbook/tutorials/](https://make.wordpress.org/training/handbook/tutorials/)
- Link to original content GitHub issue: Not created yet
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: [amitpatel0702](https://github.com/amitpatel0702), [vanpariyar](https://github.com/vanpariyar)
- Other info: Google Doc - [https://docs.google.com/document/d/1SR-t7OQ8scSUXeI9jCnO7M8vCVYEzylExHcTQGrF9tA/edit](https://docs.google.com/document/d/1SR-t7OQ8scSUXeI9jCnO7M8vCVYEzylExHcTQGrF9tA/edit)

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by Piyopiyo-Kitsune** [comment] 2023-01-10 05:50
Page preview: https://make.wordpress.org/training/?p=20466&post_type=handbook&preview=1&_ppp=4601f20741

Please approve for publication

**Comment by kaitohm** [comment] 2023-03-18 08:11
This is where the draft page currently lives. I'm leaving this note here for when we're able to publish this: https://make.wordpress.org/training/wp-admin/post.php?post=20466&action=edit

**Comment by kaitohm** [comment] 2023-03-18 08:11
@vanpariyar Please review this translation when you get a moment :-)

**Comment by vanpariyar** [comment] 2023-03-23 10:15
Hello @bsanevans, I am not able to access this link https://make.wordpress.org/training/wp-admin/post.php?post=20466&action=edit.

It redirects me to profile page

**Comment by webtechpooja** [comment] 2023-03-24 04:35
Hey @vanpariyar, 
You can check his link -
 [https://make.wordpress.org/training/?p=20466&post_type=handbook&preview=1&_ppp=027ec45ec2](https://make.wordpress.org/training/?p=20466&post_type=handbook&preview=1&_ppp=027ec45ec2)
now the public preview is available, so log-in is not compulsory.

**Comment by vanpariyar** [comment] 2023-03-24 08:54
@webtechpooja @bsanevans 
Translation looks good 

Please changes this first line 
ટ્યુટોરિયલ એ એકલ વિડિયો છે જે લર્ન વર્ડપ્રેસ પર હોસ્ટ કરવામાં આવે છે – તમે તે બધા અહીં મેળવી શકો છો:

to 👇🏼 

ટ્યુટોરિયલ એ એક વિડિયો છે. જે લર્ન વર્ડપ્રેસ પર હોસ્ટ કરવામાં આવે છે – તમે તે બધા અહીં મેળવી શકો છો:

**Comment by kaitohm** [comment] 2023-03-24 08:58
@SagarLadani Please let us know once you've evaluated/made this change.

**Comment by SagarLadani** [comment] 2023-03-27 04:11
Hello @vanpariyar and @bsanevans, I have made [this](https://make.wordpress.org/training/?p=20466&post_type=handbook&preview=1&_ppp=027ec45ec2) changes and submit for review. Please check it and let me know if anything.

**Comment by kaitohm** [comment] 2023-03-27 05:58
Thank you, @SagarLadani . Because we don't have a language switcher on the team handbook, I'm going to link your Google Doc instead of the draft page. Has the Google Doc below been updated to reflect the change, too? If so, I'll link it, and I think we can close this as done 😃 
https://docs.google.com/document/d/1SR-t7OQ8scSUXeI9jCnO7M8vCVYEzylExHcTQGrF9tA/edit

**Comment by vanpariyar** [comment] 2023-03-27 09:05
Hello @SagarLadani please update https://docs.google.com/document/d/1SR-t7OQ8scSUXeI9jCnO7M8vCVYEzylExHcTQGrF9tA/edit

As @bsanevans mentioned that he would include this document in the original tutorial.

**Comment by SagarLadani** [comment] 2023-03-27 09:10
Hello @vanpariyar , I have updated in documents.

**Comment by vanpariyar** [comment] 2023-03-27 09:13
Thanks, @SagarLadani I can confirm this document is updated.

**Comment by kaitohm** [comment] 2023-03-27 09:14
Great! This Google doc is now linked in the handbook. Thank you for translating, and reviewing it!

**Closed as completed by kaitohm** 2023-03-27 09:14 UTC
Labels: [Content] Translation
