### ISSUE TITLE
The "/lesson-plan/conditional-tags/" page design issue on mobile devices.

### ISSUE THREAD

**Issue by VipulUpadala** [WordPress/Learn#1633] opened 2023-06-15 15:41 UTC
## Description
I have reviewed the "/lesson-plan/conditional-tags/" page on my mobile devices and found the page design is breaking below the 500px screen. because of `<code>` tag does not wrap the text for that region design is breaking.   

Page URL: https://learn.wordpress.org/lesson-plan/conditional-tags/

## Step-by-step reproduction instructions

1. Open  https://learn.wordpress.org/lesson-plan/conditional-tags/ this page on mobile device.
2. Scroll down to below and check `<code>` tag does not wrap text.

## Expected behaviour
`<code>` tag need to be a responsive.

## Actual behaviour
 `<code>` tag does not responsive.

## Screenshots or screen recording (optional)
please check the below provided screenshot for a better understanding.

Screenshot: https://share.cleanshot.com/QqCPP0vsQbmYJdP1hJGC

## Environment information
- Chrome.
- Redmi note 10, Macbook

**Comment by jonathanbossenger** [comment] 2023-08-31 07:34
Hi @VipulUpadala thank you for your contribution.

The code block that is used in tutorials and lesson plans does not wrap any code inside the block by design. This is to preserve the code formatting of the example code.

I'm therefore going to close this issue, as this is an expected feature of the code block.

**Closed as completed by jonathanbossenger** 2023-08-31 07:34 UTC
Labels: [Type] Bug
