### ISSUE TITLE
Button alignment issue in Responsive

### ISSUE THREAD

**Issue by varshildoshi151189** [WordPress/Learn#815] opened 2022-07-13 05:01 UTC
Hello Team,

In wordpress.org site on below link, found that buttons are not properly aligned for responsive mobile devices (767px and below). 

**Page URL:** https://learn.wordpress.org/

Please find Screenshot for the same

Thanks
![CleanShot 2022-07-13 at 10 25 40](https://user-images.githubusercontent.com/100187481/178653952-b3cf1c29-363f-4318-872a-ee27f0cd124b.png)
.

**Comment by hlashbrooke** [comment] 2022-07-13 05:05
Thanks for logging this issue!

This is a duplicate of #734, so I'm closing this issue in favour of the existing one.

**Closed as completed by hlashbrooke** 2022-07-13 05:05 UTC
