### ISSUE TITLE
Prioritise content based on site locale switcher

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#1004] opened 2022-10-06 02:54 UTC
Content for all content types (courses, lesson plans, and tutorials) should give extra weight to content that is in the same language as what is selected in the global locale switcher. This first needs the language meta field to be added to lesson plans, courses and meetings.

**Comment by adamwoodnz** [comment] 2022-10-11 03:11
This likely depends on https://github.com/WordPress/Learn/issues/1009 for adding the language meta field.

**Comment by adamwoodnz** [comment] 2022-11-23 02:51
Language meta field is now applied to all content types. Tutorials already have this prioritisation applied, see [wporg_archive_query_prioritize_locale](https://github.com/WordPress/Learn/blob/trunk/wp-content/themes/pub/wporg-learn-2020/functions.php#L477)

**Comment by adamwoodnz** [comment] 2023-04-18 21:10
Duplicate of #939

**Closed as completed by adamwoodnz** 2023-04-18 21:10 UTC
Labels: [Type] Enhancement, [Component] Learn Plugin, Priority - High
