### ISSUE TITLE
Theme.json - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#652] opened 2022-03-02 17:04 UTC
## Related Resources

- https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/

# Topic Description
Write a description of the topic here.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.

- 

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Development Checklist:
- [ ] Gather links to Support and Developer Docs
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [ ] Create an outline of the example lesson walk-through
- [ ] Draft lesson plan
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Announce to the Training team
- [ ] Announce to lesson plan creator
- [ ] Announce to marketing
- [ ] Gather feedback from lesson plan users about the quality

# Repo Structure and Lesson Plan Template

> <span style="color:red">Please remove all blockquote comments such as this before publishing.</span>

## Description

> A short paragraph explaining what is covered in the lesson plan. This should be text that can be copied and used in a meetup or workshop description.

## Objectives

After completing this lesson, participants will be able to:

* Objective 1
* Objective 2

> It’s required that you include a bulleted list of objective(s) for each lesson plan. Objectives should be worded as actions that the participant can do once they’ve finished. See [Bloom's Taxonomy of Action Verbs](http://www.fresnostate.edu/academics/oie/documents/assesments/Blooms%20Level.pdf) (PDF) as a reference. Avoid using words like "know," "understand," "be introduced to," etc. There should be one assement item for each objective (see below).

## Target Audience

Who is this lesson intended for? What interests/skills would they bring? Put an "x" in the brackets for all that apply.

* [ ] Users / Content Writers
* [ ] Designers
* [ ] Developers
* [ ] Speakers
* [ ] Organizers
* [ ] Kids

## Experience Level

How much experience would a participant need to get the most from this lesson? Put an "x" in the brackets for all that apply.

* [ ] Beginner
* [ ] Intermediate
* [ ] Advanced

## Type of Instruction

Which strategies will be used for this lesson plan? Put an "x" in the brackets for all that apply.

* [ ] Demonstration
* [ ] Discussion
* [ ] Exercises
* [ ] Feedback
* [ ] Lecture (Presentation)
* [ ] Slides
* [ ] Show & Tell
* [ ] Tutorial

## Time Estimate (Duration)

How long will it take to present this lesson? Put an "x" in the brackets for the one that applies.

* [ ] 1 hour or less
* [ ] 2-4 hours (half-day)
* [ ] 5-8 hours (full-day)
* [ ] 2 days
* [ ] 3 days or more

## Prerequisite Skills

Participants will get the most from this lesson if they have familiarity with:

* Skill 1
* Skill 2

> _For example:_
>
> *   Experience with HTML and CSS
> *   Completed the Basic WordPress Concepts lesson

## Readiness Questions

* Question 1
* Question 2

> A list of questions for participants to see if they have the background and skills necessary to learn and understand the lesson.
>
> _For example:_
>
> *   Do you want to makes changes to your theme yourself?
> *   Do you know how to write CSS?

## Slides

> Change the `/repo-name/` in the link to match the URL name of this repo.

*   [Slides](https://wptrainingteam.github.io/lesson-plans/repo-name/slides/) (files included in this repo)

## Materials Needed

* Item 1
* Item 2

> A list of files, resources, equipment, or other materials the presenter will need for the lesson.
>
> _For example:_
>
> *   A local install of WordPress
> *   The files for the TwentySixteen theme

## Notes for the Presenter

* Note 1
* Note 2

> A list of any handy tips or other information for the presenter.
>
> _For example:_
>
> *  Participants may need to download the TwentySixteen theme before beginning
> *  What to do if there’s no projector or internet available
> *  What to do if a participant doesn’t have the necessary set up
> *  How to handle different opinions about the topic

## Lesson Outline

* First do this
* Then move on to this
* Finish with this

> The plan for the lesson. Outline form works well.
>
> _For example:_
>
> * Talk about what a theme is
> * Demonstrate how to install and activate a theme
> * Practice exercises to have participants find and install a theme on their own site

## Exercises

**Exercise name**

Short description of what the exercise does and what skills or knowledge it reinforces.

*   Short point or step of the exercise
*   And another one

> These are short or specific activities that help participants practice certain components of the lesson. They should not be fully scripted exercises, but rather something that participants could do on their own. For example, you can create an exercise based on one step of the Example Lesson.

## Assessment

There should be one assement item (or more) for each objective listed above. Each assessment item should support an objective; there should be none that don't.

**Write out the question.**

1.  Option
2.  Option
3.  Option
4.  Option

**Answer:** 3\. Correct answer

> A few questions to ask participants to evaluate their retention of the material presented. They should be a measure of whether the objectives were reached. Consider having a question for each objective.

## Additional Resources

* Resource 1
* Resource 2

> An optional section which can contain a list of resources that the presenter can use to get more information on the topic.
>
> _For example:_
>
> * Link to information on the Codex
> * Theme Review Team's Handbook

## Example Lesson

> An example of how the lesson plan can be implemented. Written in script form as one possible way an presenter might use this lesson plan at an event, with screenshots and instructions if necessary.

### Section Heading for Example Lesson

> You will likely need to break the Example Lesson down into multiple sections.

### Lesson Wrap Up

![](https://raw.githubusercontent.com/wptrainingteam/contributor-resources/master/images/lightbulb.png) Follow with the [Exercises](#Exercises) and [Assessment](#Assessment) outlined above.

**Comment by caraya** [comment] 2022-03-29 17:25
Theme.json is a moving target where features are added regularly, how would this lesson plan handle new features? would those be considered separate lesson plans or would they require updating this lesson plan?

**Comment by courtneyr-dev** [comment] 2022-03-30 00:28
We would continue to revise the existing lesson plan.

**Comment by caraya** [comment] 2022-04-05 21:24
I would like to take a shot at writing this

**Comment by courtneyr-dev** [comment] 2022-04-05 23:52
Assigned. I'll reach out for your .org username to get you access on LearnWP. We draft directly there usually.

**Comment by caraya** [comment] 2022-04-07 16:52
Is there a doc outlining what the workflow for drafting directly on LearnWP is? I'm not seeing it

**Comment by courtneyr-dev** [comment] 2022-04-07 22:51
Share how to enqueue webfonts. https://github.com/WordPress/gutenberg/pull/39988

**Comment by courtneyr-dev** [comment] 2022-04-07 23:01
Draft at https://learn.wordpress.org/wp-admin/post.php?post=15349&action=edit when you have login access @caraya - just draft on site but please do not publish. We use a standard format which I've applied already to this post.

**Comment by caraya** [comment] 2022-04-09 19:12
> Share how to enqueue webfonts. [WordPress/gutenberg#39988](https://github.com/WordPress/gutenberg/pull/39988)

This is. different than what's out in Gutenberg 12.8. 

This is adding a way to load Google fonts in a way that complies with GDPR requirements but it hasn't landed and I'm not sure if it's on track to land on 6.0. There are questions I have about this and I'm not sure where to ask them

**Comment by courtneyr-dev** [comment] 2022-04-15 11:07
It's looking like WebFonts and Theme Style Variations won't make it into 6.0. @caraya I'll update when we have a definite answer.

https://wordpress.slack.com/archives/C035NHLFUSY/p1649993897302289

**Comment by caraya** [comment] 2022-04-15 15:37
I wrote it as a feature requiring Gutenberg installed. 

I will make sure to include a note that this is not available in Core

**Comment by caraya** [comment] 2022-04-17 01:39
Ready For Review. Can't add a label to it

**Comment by westnz** [comment] 2022-05-20 02:15
Hi @caraya Could you post the link the draft lesson plan here. 👍

**Comment by caraya** [comment] 2022-05-20 20:49
> Hi @caraya Could you post the link the draft lesson plan here. 👍

Sorry, here it is

https://learn.wordpress.org/wp-admin/post.php?post=15349&action=edit

**Comment by wparasae** [comment] 2022-05-22 23:30
This is so thorough! Taking a look now:

What I love:

- Excellent readiness questions! I feel prepared for the lesson.
- Participant introductions are solid! 
- I adore the script! I am following it so far; it's concise and clear, especially if learners have some knowledge of existing coding knowledge.
- I really, REALLY like your comment about accessibility when choosing colors. Yes!
- Your outline is thorough, but would allow an instructor to do more than read the text. It's very streamlined but would allow a teacher to add their own flare to the instruction.

What could use a change:

1. QUICK FIX: Pre-Requisite: After reading the lesson plan, I would suggest adding some basic knowledge of coding languages as a pre-requisite skill, as well as familiarity with full site editing, and a general idea of what functions.php does in a classic theme.
2. Exercises: Exercises that have a little more in-depth instruction will help learners and teachers. For example, under "modify the core sections", you could have learners toggle certain things off and on (such as a border setting, a color option, etc.) and potentially adjust WHICH options are available/pre-set. Even providing 2 or 3 suggestions will help guide everyone--otherwise, they may discover they can't decide what to start with! 
3. WE CAN HELP! Assessment questions: There are a lot of two-choice answers, but I bet we could come up with a few more robust questions. Let me know if you would like suggestions! :) Happy to help.
4. QUICK FIX: I have a workshop ready that was based on this lesson plan that I can publish on using Schema with theme.json - a link out to it would set learners up for success!
5. Some screenshots of what the theme.json may do to the backend site editor will help with clarity.

I will definitely need a developer to look at this, but with my basic background knowledge, this is thorough, stream-lined, and well done. I love this! Thank you for ALL your hard work and please don't hesitate to reach out if you'd like some assistance making these changes; I just don't want to step on your toes and make them without your permission :D

**Comment by caraya** [comment] 2022-05-23 19:24
> I will definitely need a developer to look at this, but with my basic background knowledge, this is thorough, stream-lined, and well done. I love this! Thank you for ALL your hard work and please don't hesitate to reach out if you'd like some assistance making these changes; I just don't want to step on your toes and make them without your permission :D

Sarah,

Thank you for your feedback 😄 

If you want to make changes, go ahead. The goal is to make the lesson plan the best it can be, no permission needed

**Comment by caraya** [comment] 2022-06-29 03:27
This is not ready to publish yet. IT has still some work to do.

**Comment by azhiya** [comment] 2022-07-25 10:19
I've removed the "Ready to publish tag". Let us know when you're ready. Thanks.

**Comment by courtneyr-dev** [comment] 2022-07-27 16:31
https://github.com/WordPress/gutenberg/pull/40260

**Comment by caraya** [comment] 2022-07-28 22:41
@courtneyr-dev SInce I'm still working on finishing the lesson plan I'll work on incorporating this new element into the lesson plan before asking for another review

**Comment by caraya** [comment] 2022-07-29 09:40
Ready for review 😺

**Comment by caraya** [comment] 2022-09-01 20:46
Needs to incorporate the new variations block.json element. 

https://github.com/WordPress/gutenberg/pull/42539

**Comment by courtneyr-dev** [comment] 2022-10-04 17:13
Box shadow addition https://make.wordpress.org/core/2022/09/16/whats-new-in-gutenberg-14-1-15-september/

**Comment by courtneyr-dev** [comment] 2022-10-05 10:33
[outline support was also added to blocks and elements](https://github.com/WordPress/gutenberg/pull/43526) via theme.json. For more information about overall changes to theme.json, please see the [Expanded theme.json support and Styles options section below](https://docs.google.com/document/d/1MPH0lQKXLSj2Hegur_4B-wZRi_zPPJIUdXJfslO6JEo/edit#heading=h.vnuhkmgca0gc). 

Code examples: view examples provided in the [Styling elements in block themes dev note](https://make.wordpress.org/core/?p=98557&preview=true)

Adoption approach: opt-in. 

Key Make Posts/GitHub/Trac Issue(s):  

[Styling elements in block themes dev note](https://make.wordpress.org/core/?p=98557&preview=true).
[YouTube video from Dave Smith going over these new options](https://www.youtube.com/watch?v=XikXzLLojhk).

**Comment by Piyopiyo-Kitsune** [comment] 2022-11-15 01:51
Same here-- will @caraya be working on this revisions or does this require reassigment?

**Comment by caraya** [comment] 2022-11-15 03:30
The lesson plan hasn't been published. Added a first pass at the bottom with the changes and I'm trying to figure out what's the best way to do exercises for the new additions

**Comment by caraya** [comment] 2022-12-02 05:30
I've completed the first pass at the updated content.  I placed it at the bottom of the page to make it easier to review. I will move the content to its corresponding place after it has been reviewed. 

I could use help with generating assessment questions

https://learn.wordpress.org/wp-admin/post.php?post=15349&action=edit

**Comment by courtneyr-dev** [comment] 2023-01-13 23:53
6.2 ([46813](https://github.com/WordPress/gutenberg/pull/46813))

**Comment by webtechpooja** [comment] 2023-03-15 06:34
Hi @caraya   

This task is assigned to you, so I would like to ask if you have some bandwidth to work on the updates. 

If you do not find time to work on this, It's OK. Please let us know so we can open this issue again, and someone else can volunteer. 

For Context: WP 6.2 [https://github.com/WordPress/gutenberg/pull/46813](https://github.com/WordPress/gutenberg/pull/46813) You can check what needs to be updated.

Thanks

**Comment by caraya** [comment] 2023-03-15 09:46
> Hi @caraya
> 
> This task is assigned to you, so I would like to ask if you have some bandwidth to work on the updates.
> 
I'm working on the updates for 6.0, 6.1 and 6.2

Finishing up with the assessment questions before posting the draft. This was never published so there is no existing content to use the extended revision plugin with

**Comment by caraya** [comment] 2023-03-26 12:07
Content is ready for review.

**Comment by courtneyr-dev** [comment] 2023-10-11 19:47
WP 6.4
Visuals: N/A
Adoption approach: opt out via theme.json. For example with the Buttons block:
"settings": {
    "blocks": {
        "core/buttons": {
            "layout": false
        {
    { 
{

Key Make Posts/GitHub/Trac Issue(s): Allow layout controls to be disabled per block from theme.json. ([53378](https://github.com/WordPress/gutenberg/pull/53378))

**Comment by lada7042** [comment] 2023-12-19 16:21
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [ ] Learning outcomes/objectives are clear.
- [ ] Technical concepts introduced in the content are accurate.
- [ ] The speed of demonstrations are easy to follow.
- [ ] The narration audio matches what is shown visually.
- [ ] Spelling and grammar are correct.
- [ ] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

-Edit- The first (f) in the color hex code is a different font then the second and third when I look at the front end view. ![image](https://github.com/WordPress/Learn/assets/24979729/0644ecfb-49ef-4b88-bf43-8c8767616ee3)

**Comment by kaitohm** [comment] 2024-01-12 07:46
This lesson plan has been open for review for quite some time. I've done a quick pass, and have published it here: https://learn.wordpress.org/lesson-plan/how-to-configure-your-site-with-theme-json/

Some of the content is outdated (such as the fact WordPress now comes bundled with theme Twenty Twenty-Four.) But the essence remains the same and is valuable nonetheless.

If someone would like to update the lesson plan further, please create a new [Content Feedback issue](https://github.com/WordPress/Learn/issues/new/choose) and work on the updates there.

Thank you for all the work you put into creating this, @caraya 🙌

**Closed as completed by kaitohm** 2024-01-12 07:46 UTC
Labels: Priority - Medium
