### ISSUE TITLE
Syntax Highlighter bug

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#158] opened 2020-11-25 16:39 UTC
https://wordpress.slack.com/archives/C02RW657Q/p1606294799320300 

Poojah indicates 

I am reviewing the code snippets and the end tag works fine in admin section but on frontend it doesn't work properly, end tag entity converts into " &gt;"
For example check this lesson plan, https://learn.wordpress.org/lesson-plan/template-tour/
I am using same plugin for one of my personal website and it works fine there, please update plugin if it is outdated and check it's settings  (if something is wrong there) also frontend and admin both screenshots are attached, please have a look.

I have logged in to see the same issue occurs for me as well.

**Comment by jrastaban** [comment] 2020-12-01 23:51
This is occurring on the loop page I was working on so I did some digging. It looks like we aren't the only ones who ran into this: https://github.com/Automattic/syntaxhighlighter/issues/108  

It is currently marked as closed so I'm not sure an update will fix it. It looks to be an issue that came up but was never resolved.

In this duplicate issue https://github.com/Automattic/syntaxhighlighter/issues/159 
Someone said only their editors had this issue which might be why it has been hard to reproduce. Unsure about Poojah but I know I'm accessing it as an editor... so you know, confirmation bias 😁   
Anyway that leads me to suspect that the real issue is an underlying conflict when users don't have the [unfiltered_html ](https://wordpress.org/support/article/roles-and-capabilities/#unfiltered_html)capability.

**Closed as completed** 2020-12-04 17:29 UTC
Labels: [Type] Bug
