### ISSUE TITLE
Bug report: learn.wordpress filter dropdown faulty 

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#810] opened 2022-07-08 01:22 UTC
## Description
The filter dropdown on the WordPress Learn website is not working properly. When you click on a filter it closes. 

## Step-by-step reproduction instructions
Please list the steps needed to reproduce the bug. For example:
1. Go to https://learn.wordpress.org/workshops/
2. Click on one of the filters

## Expected behaviour

I expected the dropdown filter to stay open.

## Actual behaviour

The filter dropdown closes when you click on it.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/89751452/177898053-e55c7d5e-809c-4dab-b0e9-377ee208bae2.mov

## Environment information
- I am using Chrome
- I am using a Macbook Pro

**Comment by adamwoodnz** [comment] 2022-07-08 03:50
I can't reproduce this in my local environment, but I'll try my sandbox now. Production has many more plugins activated than local though. @westnz do you know if any of them have been added/activated recently?

**Comment by westnz** [comment] 2022-07-08 04:41
Thanks @adamwoodnz.  We don’t have any new plugins on there that I’m aware of.

**Comment by westnz** [comment] 2022-07-08 04:43
I could reproduce it when I tried it in Safari as well, and without being logged in.

**Comment by vagelisp** [comment] 2022-07-08 21:43
I can reproduce this on both Chrome and Safari on a Macbook Pro.
As you can see in the video, you can keep it open if you click on the right side of the arrow, but if you click anywhere else, the selector picks the first available option. Clear filter [x] also doesn't work.

https://user-images.githubusercontent.com/9304640/178074109-c87f6aa5-2a18-45aa-983d-7a96a77136fb.mov

**Comment by adamwoodnz** [comment] 2022-07-11 00:51
Yep definitely not arguing about reproducibility! Broken in all browsers in prod for me, and also in my sandbox. I'm continuing to debug this week.

**Comment by kaitohm** [comment] 2022-11-09 21:25
I've confirmed this has now been fixed in Chrome, Firefox and Safari. Closing.

**Closed as completed by kaitohm** 2022-11-09 21:25 UTC
Labels: [Type] Bug
