### ISSUE TITLE
Lesson - Using the comments block

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#508] opened 2022-03-02 16:15 UTC
//tutorial

**Comment by azhiya** [comment] 2022-03-30 19:07
Hi @westnz. I'm backtracking and updating the labels and milestones.

**Comment by azhiya** [comment] 2022-04-22 10:58
I deleted 662 as this was a duplicate of 508.

**Comment by courtneyr-dev** [comment] 2022-07-27 14:50
https://github.com/WordPress/gutenberg/pull/40419 
See also: https://make.wordpress.org/core/2022/04/28/whats-new-in-gutenberg-13-1-27-april/
Minor improvement

**Comment by courtneyr-dev** [comment] 2022-10-05 10:25
[Merge Comments and Post Comments blocks](https://github.com/WordPress/gutenberg/pull/41807#top)
For prior discussion, you can view this previous issue that laid the groundwork: [Post Comments block: Merge Comments Query Loop block](https://github.com/WordPress/gutenberg/issues/40521#top).

**Comment by Piyopiyo-Kitsune** [comment] 2022-11-15 01:54
@westnz will you be working on these revisions or does this require reassignment?

**Comment by westnz** [comment] 2022-11-15 02:04
Will get to this 👍

**Comment by westnz** [comment] 2022-11-25 03:22
Updated version ready for review: 

Please note, the name of the Post Comments block has changed to Comments block.

https://user-images.githubusercontent.com/89751452/203893932-65123d0a-d5be-45d8-a67e-6b119460f0e8.mp4

**Comment by amitpatel0702** [comment] 2022-11-29 13:01
Thanks @westnz for an amazing tutorial on the Comment block. Here are my notes

- Sentence case for every headline will make it more readable and effective.
- Sentence case for every headline will make it more readable and effective.
- Can we mention somewhere - Comment block is specific to template and not to data. i.e page will display page comments and post will display post specific comments.

**Comment by westnz** [comment] 2022-11-29 19:57
Thank you for the feedback @amitpatel0702

**Comment by amitpatel0702** [comment] 2022-12-06 07:41
Can we label the above as review1 complete?

**Comment by westnz** [comment] 2022-12-06 20:18
Thanks for the reminder @amitpatel0702. I think you can also do this once you complete a review in GitHub 👍

**Comment by westnz** [comment] 2022-12-16 01:16
Published: https://learn.wordpress.org/tutorial/displaying-the-post-comments-block-in-block-themes/

**Comment by westnz** [comment] 2024-04-05 03:52
https://github.com/WordPress/Learn/assets/89751452/b566b274-1360-46cf-aaa0-9a1540c2be36

**Comment by ironnysh** [comment] 2024-04-12 14:12
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great tutorial, @westnz. I liked that you mentioned the added value of comments, rather than focusing only on the technical side.

**Comment by digitalchild** [comment] 2024-04-18 05:05
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great tutorial that is easy to follow and to the point. Will you provide a link in the text to the managing spam video you mention?

**Comment by westnz** [comment] 2024-04-18 21:09
Thank you @digitalchild and @ironnysh for the feedback!

Good idea to link the spam video below resources.

**Comment by westnz** [comment] 2024-04-30 01:21
Published as part of the Intermediate User learning pathway in Sensei.

**Closed as completed by westnz** 2024-04-30 01:21 UTC
Labels: [Content] Published
