### ISSUE TITLE
Greek translation for "Submitting Block Patterns to the Directory" lesson plan

### ISSUE THREAD

**Issue by vagelisp** [WordPress/Learn#817] opened 2022-07-13 23:34 UTC
# Topic Description
Greek translation for [Submitting Block Patterns to the Directory](https://learn.wordpress.org/lesson-plan/submitting-block-patterns-to-the-directory/) lesson plan

# Related Resources
The original Lesson Plan
[Submitting Block Patterns to the Directory](https://learn.wordpress.org/lesson-plan/submitting-block-patterns-to-the-directory/)

The translated version of the Lesson Plan in google docs
https://docs.google.com/document/d/1Aent7pu1Sy2kyzlDdCNjRAZti7qkXiv6YYuKIytiRFw/

**Comment by kaitohm** [comment] 2022-07-15 10:47
This is currently being reviewed by @lenasterg ([Slack link](https://wordpress.slack.com/archives/C02RP50LK/p1657870170640919))

**Comment by lenasterg** [comment] 2022-07-19 07:26
Hi. 
The review is completed. 

It's OK to publish

**Comment by kaitohm** [comment] 2022-07-19 08:21
@vagelisp Here is a duplicate of the English lesson plan. Could you replace the English text in this with your translated Greek text? https://learn.wordpress.org/wp-admin/post.php?post=19724&action=edit Let me know if you have issues accessing that.

**Comment by vagelisp** [comment] 2022-07-19 08:22
Thanks, @bsanevans. I'll get it done asap.

**Comment by vagelisp** [comment] 2022-07-19 09:33
hi @bsanevans the draft is ready for you to review. I replaced its content with the Greek translation.

**Comment by kaitohm** [comment] 2022-07-20 02:18
This looks great! I've published the lesson plan here: [Υποβολή Μοτίβων μπλοκ (Block Patterns) στον κατάλογο.](https://learn.wordpress.org/lesson-plan/%cf%85%cf%80%ce%bf%ce%b2%ce%bf%ce%bb%ce%ae-%ce%bc%ce%bf%cf%84%ce%af%ce%b2%cf%89%ce%bd-%ce%bc%cf%80%ce%bb%ce%bf%ce%ba-block-patterns-%cf%83%cf%84%ce%bf%ce%bd-%ce%ba%ce%b1%cf%84%ce%ac%ce%bb%ce%bf/)

Thanks for your contributions, @vagelisp and @lenasterg !

**Closed as completed by kaitohm** 2022-07-20 02:18 UTC
Labels: [Content] Translation
