### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by moranjosep** [WordPress/Learn#1712] opened 2023-07-13 20:15 UTC
## Description
 when taking the Best Practices for Global courses, the second lesson is 100% completed but when leaving the course it is not reflected as complete.

## Expected behaviour
 Step 1 and step 2 correct. You can take the course without any problem and answer the test questions.

At the end of the course, it should appear as completed with 100% of the lessons completed and the tests corresponding to each lesson completed.

## Actual behaviour
 Step 1 and step 2 correct. You can take the course without any problem and answer the test questions.

At the end of the course it does not appear as a finished course, it appears as an active and unfinished course.

## Screenshots or screen recording (optional)

![Captura de pantalla 2023-07-13 a las 8 09 29 (2)](https://github.com/WordPress/Learn/assets/139503566/9b7b7868-93c3-4d9a-bcc4-7b9489fb8ddb)
![Captura de pantalla 2023-07-13 a las 8 23 33 (2)](https://github.com/WordPress/Learn/assets/139503566/3f20ab14-f568-4d2c-8355-2cd4aad76df5)
![Captura de pantalla 2023-07-13 a las 21 16 46 (2)](https://github.com/WordPress/Learn/assets/139503566/9017d12d-d5b4-4f8f-9e26-de398e8b360f)
![Captura de pantalla 2023-07-13 a las 21 16 38 (2)](https://github.com/WordPress/Learn/assets/139503566/d5640dfa-07c7-41ce-a462-bf204a0dedc4)
![Captura de pantalla 2023-07-13 a las 21 23 54 (2)](https://github.com/WordPress/Learn/assets/139503566/30c11b5d-f332-43a3-aa0e-949e89d3e846)

## Environment information
- Browser(s) are you seeing the problem on.
- Device you are using and operating system (e.g. "Desktop with Windows 10", "iPhone with iOS 14", etc.).
- Apple Macbook pro M2  macOS Ventura 13.4.1

**Comment by donnapep** [comment] 2023-10-25 10:07
I tested this but was unable to reproduce. Here's what I did:

- Clicked the _Take Course_ button on [this page](https://learn.wordpress.org/course/writing-in-the-wordpress-voice/).
- Took the quiz from the first lesson. Ensured I answered all the questions correctly.
- Clicked the _Continue to Next Lesson_ button.
- Took the quiz from the second lesson. Ensured I answered all the questions correctly.
- I was taken to the Course Completed page where the lessons were 100% completed.
- Navigated to `https://learn.wordpress.org/my-courses/?my_courses_status=complete` and saw the following:

![Screenshot 2023-10-25 at 12 00 31 PM](https://github.com/WordPress/Learn/assets/1190420/80c82609-2af7-4d54-9333-14d755aed49b)

I suspect it's safe to close this one.

**Closed as completed** 2024-12-02 01:06 UTC
Labels: [Type] Bug, [Component] Sensei, [Dev] Needs Testing
