### ISSUE TITLE
Fix pagination for lesson plans

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#174] opened 2020-12-14 10:57 UTC
It looks like something is up with the lesson plans pagination - some lesson plans are being shown multiple times as you page through the archive, even though the total number (7 pages with a maximum of 9 on each page) is the correct amount we're seeing plenty of the individual plans being repeated. I can't think what's causing this.

This Trac ticket has more details and screenshots: https://meta.trac.wordpress.org/ticket/5544

**Comment by hlashbrooke** [comment] 2020-12-14 11:06
The archive template for lesson plans looks pretty standard, so it doesn't look like there's an issue there. This function modifies the archive query: https://github.com/WordPress/learn/blob/trunk/wp-content/themes/pub/wporg-learn-2020/functions.php#L270, but as far as I can tell that only acts on any selected filters and shouldn't cause this issue.

**Comment by coreymckrill** [comment] 2020-12-14 18:17
I think this is a duplicate of #116

**Closed as completed by coreymckrill** 2020-12-14 18:17 UTC
