### ISSUE TITLE
How to build a responsive WordPress site

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2303] opened 2024-03-07 05:46 UTC
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan):
- Content title: How WordPress helps you create a responsive Design
- Topic description:  
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Advanced

# Learning Objectives

# Related Resources and Other Notes

**Comment by digitalchild** [comment] 2024-03-07 05:46
//lessons

**Comment by westnz** [comment] 2024-07-31 03:58
Script: https://docs.google.com/document/d/1FXWBWxlcesQnypVFN2xIg37uRO1NQdnDOWxzh1H7pVw/edit#heading=h.nf261scq61ge

**Comment by westnz** [comment] 2024-08-02 03:24
https://github.com/user-attachments/assets/8394e6b1-984e-4312-8b53-f062d6375e35

**Comment by westnz** [comment] 2024-08-02 03:27
Please also let me know if this is a good title for the lesson or does it need to change? Any other suggestions?

**Comment by noruzzamans** [comment] 2024-08-02 09:57
@westnz I think your title is good for this lesson. However, I suggest using the title 'How to Build a Fully Responsive WordPress Website.' This title is more likely to be SEO-friendly due to its specificity, keyword optimization, and alignment with user intent. I added the word 'fully' and updated 'site' to 'website.'

Fully Responsive: The term 'fully responsive' adds an extra layer of specificity, which could attract users looking for comprehensive solutions.

Website: The word 'website' is more commonly searched and might align better with what users typically type into Google.

**Comment by Soir7** [comment] 2024-08-02 23:46
**Confirmed**:

x  Learning outcomes/objectives are clear.
x  Technical concepts introduced in the content are accurate.
x  The speed of demonstrations are easy to follow.
x  The narration audio matches what is shown visually.
x  Spelling and grammar are correct.
x  Sound quality is consistent throughout the video.
x  [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and   [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
o  Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comments**:

1. Regarding lesson **title**. I did some SEO research.  Based on the results, adding the word 'fully' to the title is not necessary. Also, at this point, it is generally understand that responsive is comprehensive of various devices/screen sizes.  

I concur with @noruzzamans in his suggestion to change **site** to **website**. 

Nice job on video. Clear, simple, directly conveyed.

Thanks, @westnz

**Comment by ironnysh** [comment] 2024-08-03 18:35
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great lesson, @westnz!

Only thing I’m missing is a closing slide.

**Comment by westnz** [comment] 2024-08-04 21:26
Thank you for reviewing, folks!

**Comment by lada7042** [comment] 2024-08-06 17:08
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [ ] Learning outcomes/objectives are clear.
- [ ] Technical concepts introduced in the content are accurate.
- [ ] The speed of demonstrations are easy to follow.
- [ ] The narration audio matches what is shown visually.
- [ ] Spelling and grammar are correct.
- [ ] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

**Comment by westnz** [comment] 2024-08-07 23:33
//published

**Closed as completed** 2024-08-07 23:33 UTC
Labels: [Content] Published
