### ISSUE TITLE
Add Learn link to the WP.org menu

### ISSUE THREAD

**Issue by azhiya** [WordPress/Learn#170] opened 2020-12-11 12:51 UTC
We've forgotten about this, please add Learn to the [WP.org](https://wordpress.org) menu.

Thanks to @oglecker for brining it to our attention.

**Comment by azhiya** [comment] 2020-12-11 12:52
@coreymckrill Apologies, I don't fully know the process but I think this one might be for you.

**Comment by hlashbrooke** [comment] 2020-12-15 01:24
We would need to get approval for this, but I feel like it would make sense to have "Learn" as a top-level item in the top navigation menu.

**Comment by hlashbrooke** [comment] 2020-12-15 03:21
I have confirmed that we have the approval to add a "Learn" item to the top-level navigation menu appearing after "Showcase".

**Comment by azhiya** [comment] 2020-12-15 05:24
That’s great. Thank you all.

**Comment by dd32** [comment] 2020-12-15 06:56
Fixed on WordPress.org via r16779-dotorg.

**Closed as completed by dd32** 2020-12-15 06:56 UTC
Labels: [Component] Learn Theme

**Comment by dd32** [comment] 2020-12-15 06:58
Also to note, that it's only been added to the main WordPress.org site, not on every localised site (ie. en-au.wordpress.org doesn't have it).

If it's wanted on localised sites, we'll have to follow up on https://meta.trac.wordpress.org/ticket/1201

The link in the footer via #164 is on all sites, english or internationalised.

**Comment by azhiya** [comment] 2020-12-15 11:50
@coreymckrill sorry but can we change the Footer link to "Learn WordPress" instead of "Learn"? It's fine as Learn on the header menu.

Looks like the Trac pages have the same issue as localised sites. Hmm, the footer on Trac pages will also need a link to Learn WordPress. I'll add a note to the Trac ticket https://meta.trac.wordpress.org/ticket/1201

**Comment by coreymckrill** [comment] 2020-12-15 21:01
@azhiya why do you think adding "WordPress" to the Learn link is important in the footer? I'm hesitant to do that because the word "WordPress" already appears several times there and it seems like it would add visual clutter.

**Comment by dd32** [comment] 2020-12-16 00:52
For what it's worth, I simply used `Learn` since that's what we used in the past when it was there (I put it in the same place too).

I don't think suffixing WordPress there will help anything, almost every item in the footer could have `WordPress` suffixed to it.

**Comment by azhiya** [comment] 2020-12-16 11:13
@coreymckrill and @dd32 I'll get back to you on this one as the request came via Marketing. _Note to self to make sure she gets clarity on exactly why a change is required._
