### ISSUE TITLE
The Editor is displaying strangely when creating a post

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#915] opened 2022-09-01 01:02 UTC
## Description

When I created a new post, the title and lists were displayed in the middle of the page. The text is also displayed very widely.

## Expected behaviour

The title, lists and text are all aligned normally. 

## Actual behaviour

When I created a new post, the title and lists were displayed in the middle of the page. The text is also displayed very widely.

## Screenshots or screen recording (optional)

<img width="1912" alt="image" src="https://user-images.githubusercontent.com/89751452/187809899-47673bc4-dfd5-423a-b45a-cf2dff6fce50.png">,

<img width="1912" alt="image" src="https://user-images.githubusercontent.com/89751452/187810517-a9716c79-32dd-4f45-9442-4809d1e0c6ad.png">

## Environment information
- Browser(s) are you seeing the problem on: Chrome
- Device you are using and operating system: Macbook Pro

**Comment by kaitohm** [comment] 2022-11-09 23:06
I opened [the post in question](https://make.wordpress.org/training/wp-admin/post.php?post=19468&action=edit), and I also create a new post, but I couldn't reproduce the issue in either case.

If this is still an issue, please share steps to recreate this. If you're copying content in from another application, it could be bringing in styling from that other application.

Otherwise, an update to the site/editor could have fixed this. I'm closing this for now 🙂

**Closed as completed by kaitohm** 2022-11-09 23:06 UTC
Labels: [Type] Bug, [Component] Environment
