### ISSUE TITLE
Feedback - Broken Images in some Lessons 

### ISSUE THREAD

**Issue by kspilarski** [WordPress/Learn#2561] opened 2024-06-23 13:45 UTC
## Type of feedback
//content

## Description
There are broken images `"This XML file does not appear to have any style information associated with it. The document tree is shown below."` in: 

-  https://learn.wordpress.org/lesson/how-to-log-in-with-wp-admin/ the ‘Remember Me’ Checkbox

<img width="1028" alt="Screenshot 2024-06-23 at 15 17 31" src="https://github.com/WordPress/Learn/assets/36863633/de6403d2-37e8-4fe0-bc4e-3bb2c5f29fb0">

- https://learn.wordpress.org/lesson/lets-talk-wordpress-login-security/ "How do I know if I’m logged in?"

<img width="1014" alt="Screenshot 2024-06-23 at 15 41 31" src="https://github.com/WordPress/Learn/assets/36863633/f5b97204-f10c-4ef4-9d90-d1d544967508">

- https://learn.wordpress.org/lesson/a-hands-on-experiment-with-the-block-editor/ before "Basic settings in the block editor"

<img width="1033" alt="Screenshot 2024-06-23 at 15 24 24" src="https://github.com/WordPress/Learn/assets/36863633/38399787-5856-43f0-8160-ac196bbdfa11">

- https://learn.wordpress.org/lesson/get-found-using-the-media-library/ before "The media library options"

<img width="1018" alt="Screenshot 2024-06-23 at 15 29 17" src="https://github.com/WordPress/Learn/assets/36863633/02de8b8a-6840-4be6-bd24-859758dbd3ed">

---

And it might be helpful to add images in the quiz https://learn.wordpress.org/quiz/a-hands-on-experiment-with-the-block-editor/  
<img width="537" alt="Screenshot 2024-06-23 at 15 27 23" src="https://github.com/WordPress/Learn/assets/36863633/ee001af6-391d-40a8-9ac1-117885e99ef3">

**Comment by ironnysh** [comment] 2024-09-12 10:45
Duplicate of several other issues tackled today:

- [ ] #2346 
- [ ] #2581
- [ ] #2583 

I'll close this one (cc @WordPress/learn-editors)

Thanks for reporting, @kspilarski!

**Closed as completed by ironnysh** 2024-09-12 10:45 UTC
Labels: [Content] Feedback
