### ISSUE TITLE
[Related Course: Create a Custom Block Theme #1] Saving Your Work: Create Block Theme - Lesson Plan

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#853] opened 2022-07-22 18:12 UTC
### **IMPORTANT:** 
** This lesson plan belongs to part of a greater course, [Create a Custom Block Theme #1](https://github.com/WordPress/Learn/issues/631) **
**Please reach out to @arasae (Sarah Snow) in the #training team Slack if you would like to help with this lesson plan.**

# Topic Description
Once someone has finished creating their custom theme, they will want to export it. This lesson aims to talk about why they need to export it, when in the process this should be done, and what exporting ultimately gains them. 

## Objectives

After completing this lesson, participants will be able to:

* Describe the process of exporting their custom theme
* Export a finished custom theme
* Take a screenshot of their finished theme and include it with their files
* Analyze the differences between an exported and non-exported theme (? might need work)

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Development Checklist:
- [ ] Review any related material on Learn
- [ ] Description and Objectives finalized
- [ ] Gather links to Support, other learn.wordpress.org existing resources, and Developer Docs
- [ ] Create an outline of the example lesson walk-through
- [ ] Draft lesson plan
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Announce to the Training team
- [ ] Announce to lesson plan creator
- [ ] Announce to marketing
- [ ] Gather feedback from lesson plan users about the quality

# Repo Structure and Lesson Plan Template

> <span style="color:red">Please remove all blockquote comments such as this before publishing.</span>

## Description

> A short paragraph explaining what is covered in the lesson plan. This should be text that can be copied and used in a meetup or workshop description.

## Target Audience

Who is this lesson intended for? What interests/skills would they bring? Put an "x" in the brackets for all that apply.

* [x] Users / Content Writers
* [x] Designers
* [x] Beginner-Level Developers
* [ ] Developers
* [ ] Speakers
* [ ] Organizers
* [ ] Kids

## Experience Level

How much experience would a participant need to get the most from this lesson? Put an "x" in the brackets for all that apply.

* [ ] Beginner
* [x] Intermediate
* [ ] Advanced

## Type of Instruction

Which strategies will be used for this lesson plan? Put an "x" in the brackets for all that apply.

* [x] Text-and-Image-Based, Remote-First Course
* [ ] Exercises
* [ ] Slides
* [ ] Video Tutorial

## Time Estimate (Duration)

How long will it take to present this lesson? Put an "x" in the brackets for the one that applies.
* [ ] 1-5 Minutes
* [ ] 5-10 Minutes
* [ ] 15+ Minutes
* [ ] 1 hour or less

## Prerequisite Skills

Participants will get the most from this lesson if they have familiarity with:
_These are important to include in case someone wants to use this lesson plan in-person as a stand-alone lesson._
* Skill 1
* Skill 2

> _For example:_
>
> *   Experience with HTML and CSS
> *   Completed the Basic WordPress Concepts lesson

## Readiness Questions
_These are important to include in case someone wants to use this lesson plan in-person as a stand-alone lesson._
* Question 1
* Question 2

> A list of questions for participants to see if they have the background and skills necessary to learn and understand the lesson.
>
> _For example:_
>
> *   Do you want to makes changes to your theme yourself?
> *   Do you know how to write CSS?

## Slides
_If someone wanted to run this lesson as a stand-alone Online Live Workshop or at an in-person WordCamp, you could create slides for this here; if you run a Live Online Workshop on one of these topics or find someone else has, related slides would be welcome!_

> Change the `/repo-name/` in the link to match the URL name of this repo.

*   [Slides](https://wptrainingteam.github.io/lesson-plans/repo-name/slides/) (files included in this repo)

## Materials Needed

* Item 1
* Item 2

> A list of files, resources, equipment, or other materials the presenter will need for the lesson.
>
> _For example:_
>
> *   A local install of WordPress
> *   The files for the TwentySixteen theme

## Notes for the Presenter
_/Include any tips needed to present this topic for a Live Online Workshop or in an in-person classroom setting._

* Note 1
* Note 2

> A list of any handy tips or other information for the presenter.
>
> _For example:_
>
> *  Participants may need to download the TwentySixteen theme before beginning
> *  What to do if there’s no projector or internet available
> *  What to do if a participant doesn’t have the necessary set up
> *  How to handle different opinions about the topic

## Lesson Outline

* First do this
* Then move on to this
* Finish with this

> The plan for the lesson. Outline form works well.
>
> _For example:_
>
> * Talk about what a theme is
> * Demonstrate how to install and activate a theme
> * Practice exercises to have participants find and install a theme on their own site

## Exercises
_What someone will DO with what they learn in each lesson; most lessons have at least one related exercise._

**Exercise name**

Short description of what the exercise does and what skills or knowledge it reinforces.

*   Short point or step of the exercise
*   And another one

> These are short or specific activities that help participants practice certain components of the lesson. They should not be fully scripted exercises, but rather something that participants could do on their own. For example, you can create an exercise based on one step of the Example Lesson.

## Assessment
_These assessments will be autograded on Learn.WordPress.org._
There should be one assessment item (or more) for each objective listed above. Each assessment item should support an objective; there should be none that don't.

**Write out the question.**

1.  Option
2.  Option
3.  Option
4.  Option

**Answer:** 3\. Correct answer

> A few questions to ask participants to evaluate their retention of the material presented. They should be a measure of whether the objectives were reached. Consider having a question for each objective.

## Additional Resources

* Resource 1
* Resource 2

> An optional section which can contain a list of resources that the presenter can use to get more information on the topic.
>
> _For example:_
>
> * Link to information on the Codex
> * Theme Review Team's Handbook

## Example Lesson [Written for a text-and-image based, multimedia course rather than for a live classroom setting]

> An example of how the lesson plan can be implemented. Written in script form as one possible way an presenter might use this lesson plan at an event, with screenshots and instructions if necessary.

### Section Heading for Example Lesson

> You will likely need to break the Example Lesson down into multiple sections.

### Lesson Wrap Up

![](https://raw.githubusercontent.com/wptrainingteam/contributor-resources/master/images/lightbulb.png) Follow with the [Exercises](#Exercises) and [Assessment](#Assessment) outlined above.

**Comment by wparasae** [comment] 2022-12-27 19:34
This lesson is ready for review - [preview this lesson here](https://learn.wordpress.org/?post_type=lesson&p=26849&preview=true). 

Please leave feedback below. Specifically, I'm looking for feedback on...

- Clarity: Was it clear what was happening and why? 
- Is the terminology correct? I feel like I didn't explain this as well as I could have and am curious as to your thoughts. I feel like this is missing some vocabulary that could be added to better set folks up for success.
- Video sound quality: I was super sick when recording this, so I may need to make some changes.

**Comment by jasonsnow12** [comment] 2022-12-27 20:58
Typos:
- There seems to be missing something (an image) here? `Here is an example of the same theme’s user preferences that have become hard-coded into the theme:`
- Under "Why make your preferences permanent?": remove this a `With user preferences, if **a** you or a user makes lots of changes to their theme, realizes they want to start all over, and resets their work to the defaults, all their choices (color, sizing, padding, etc.) in Global Styles reset to the theme’s defaults.`
- `If you don’t save your preferences to the theme’s database itself, **when** a new user goes to install your theme, they will simply see a blank theme.`

Clarity:
Overall, yes, very clear. The plugin makes it simple to quickly update the theme settings, although I am curious about if other users can make "User" default changes in the theme?

Video sound:
Sounded clear to me.

Terminology:
I have no idea. "Save" could be "Implemented"? Otherwise it was easy to follow, so probably good for the audience.

**Comment by wparasae** [comment] 2023-01-10 18:44
Contributor feedback: 

https://d.pr/i/2lhFxA

**Comment by jonathanbossenger** [comment] 2023-01-11 08:26
Great module @wparasae I love how you've introduced Create Block Theme by highlighting one of its features, but listing the rest.

A couple of thoughts:

- _user preference - I worry that the use of preference for these changes could confuse folks with the [editor preferences](https://gutenberghub.com/how-to-configure-preferences-of-wordpress-block-editor/). I've always preferred (irony) to use the term _user changes_, which also aligns with the language in Create Block Theme. Unless this was confirmed as the official term for these changes, in which case, ignore me, and I'll start using that term.
- _Use the open-source, WordPress.org sponsored plugin, [Create Block Theme](https://wordpress.org/plugins/create-block-theme/)_ I think the use of the word "sponsored" here might be slightly incorrect. I do get what you're trying to convey, it's essentially built and managed by a team that's sponsored to work on it, but being sponsored by WordPress.org and being sponsored by a company like Automattic are two slightly different things.

**Comment by wparasae** [comment] 2023-01-12 21:01
@jonathanbossenger - These are excellent points, Jonathan. I have changed "preferences" to "changes" - we can always iterate upon them later. Thank you for your feedback!

**Comment by wparasae** [comment] 2023-01-12 21:09
Changes made; module published!

**Comment by fikekomala** [comment] 2023-01-13 07:23
Great job @wparasae! Here's a few notes: 

- I don't think these images (_manually exporting your theme_ and _create block theme options_) is explained clearly enough 
![image](https://user-images.githubusercontent.com/27950076/212259738-93632e55-36f6-4302-b04a-19b8531f66d3.png)
![image](https://user-images.githubusercontent.com/27950076/212260532-0bbc3977-2928-47dc-8abf-54d2de051eb1.png)

- Small fix: missing 'is'. "(This plugin maintained by contributors through WordPress.org)"
- The sound quality of the video is great! But there's a 30-second silence at the end. Is it on purpose?

**Comment by kaitohm** [comment] 2023-12-05 04:38
Moving this to the Feedback project board.

Please view the last comment as feedback provided to [the published content](https://learn.wordpress.org/lesson/saving-your-work-create-block-theme/). Then, follow [Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues) to validate this feedback.

**Comment by jonathanbossenger** [comment] 2024-02-15 07:23
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? (Yes or No): Yes, but the images are pretty clear. 
- What should happen next to apply the feedback?: Fix the missing "is"

**Comment by jonathanbossenger** [comment] 2024-02-15 07:23
Edited the lesson to fix the missing "is"

**Closed as completed by jonathanbossenger** 2024-02-15 07:23 UTC
Labels: Awaiting Triage, [Content] Feedback
