### ISSUE TITLE
Feedback - Broken Image on how to login with wp-admin tutorial

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#2581] opened 2024-06-30 16:33 UTC
## Description

On the tutorial Getting Started With WordPress: Get Familiar, Under "The 'Remember Me' Checkbox" headline there is a broken image path. 

On the tutorial Getting Started With WordPress: Get Familiar, Under "How do I know if I’m logged in?" headline there is a broken image path. 

## Screenshots or screen recording (optional)

<img width="1282" alt="image" src="https://github.com/WordPress/Learn/assets/122839775/da2a5224-a0ad-4e6c-9e48-4d86cbaf5909">

<img width="1282" alt="image" src="https://github.com/WordPress/Learn/assets/122839775/af7256b5-1da4-4410-b00a-3a05c5058dea">

## Other information (optional)

The url to the lesson is https://learn.wordpress.org/lesson/how-to-log-in-with-wp-admin/

**Comment by ironnysh** [comment] 2024-09-12 10:39
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? Yes and No :-) 


### No
> On the tutorial Getting Started With WordPress: Get Familiar, Under "The 'Remember Me' Checkbox" headline there is a broken image path.

This has been [fixed](https://learn.wordpress.org/lesson/how-to-log-in-with-wp-admin/) (see screenshot below):
![Image](https://github.com/user-attachments/assets/2c7d0ecd-3aab-4445-90a7-6a67371aca32)

### Yes
> On the tutorial Getting Started With WordPress: Get Familiar, Under "How do I know if I’m logged in?" headline there is a broken image path.

This is a duplicate of #2346. See provided fix there. (link to the relevant lesson: https://learn.wordpress.org/lesson/lets-talk-wordpress-login-security/)

@WordPress/learn-editors

**Closed as completed by ironnysh** 2024-09-12 10:39 UTC
Labels: [Content] Feedback

**Comment by ghost** [comment] 2024-09-12 15:17
Thank you :)

**Comment by ironnysh** [comment] 2024-09-12 16:37
Thanks for reporting, @j0eybrinkman :-)
