### ISSUE TITLE
Feedback - Preview as Student is confusing

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2852] opened 2024-08-21 22:26 UTC
## Type of feedback

The 'Preview as Student' tab is confusing. One of the learners stated, "I thought I was already a student since I'm logged in and taking the course. Once I clicked the button, it was a weird or confusing experience. What is the purpose, etc.?" 

I never noticed this, but I am also confused as to why it is there. When I start a course, I should be automatically logged in as a student. 
## Description

I think this tab should be removed and a learner should automatically be logged in as student.

## Step-by-step reproduction instructions (optional)

1. Go to a course such as https://learn.wordpress.org/lesson/global-theme-settings/?

## Screenshots or screen recording (optional)

https://github.com/user-attachments/assets/48e8a1bf-9485-4adb-890c-3097c4f18898

**Comment by jonathanbossenger** [comment] 2024-08-22 07:15
~This link is a Sensei feature that's only supposed to show to course creators, so that they can preview the content as a student might see it. I confirmed this with a separate testing .org account, and can confirm it appears when it shouldn't.~

EDIT: I made a small mistake here, seems the test user I was using was given Edit permissions at some point. So this seems to be expected for certain user types.

@westnz can you check, does the person who reported this have any Edit permissions on Learn WordPress? That would explain why this option is being shown to them.

**Comment by westnz** [comment] 2024-08-22 22:30
Ah, I checked, and the user has an Editor role.

**Comment by jonathanbossenger** [comment] 2024-08-23 07:05
Yup, that would explain why it's happening. Closing this out then.

**Closed as completed by jonathanbossenger** 2024-08-23 07:05 UTC
Labels: [Type] Bug, [Component] Sensei
