### ISSUE TITLE
Lesson: Use the Create Block Theme plugin for exports, and theme variations

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2552] opened 2024-06-18 22:10 UTC
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Use the Create Block Theme plugin for exports, and theme variations
- Topic description: 
Save/export functionality
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Advanced

# Related Resources and Other Notes

### Automation Code

//lesson

**Comment by ervanyuff** [comment] 2024-08-08 05:24
Hi team, I would like to be involved in editing this video 📹

**Comment by westnz** [comment] 2024-08-08 08:50
Thank you @ervanyuff. I will send the script and resources through tomorrow.

**Comment by westnz** [comment] 2024-08-11 22:44
The script, voice recording and additional screen recordings have been sent.

**Comment by ervanyuff** [comment] 2024-08-23 02:00
~Hi team, here is [Use the create block theme plugin](https://drive.google.com/file/d/1X3msNeUEAscQ1bQP2khvtw1MBacUkGW5/view?usp=sharing) video. Please feel free to provide any feedback. Thank you 🙏~

**Comment by westnz** [comment] 2024-08-23 03:23
Thank you, Ervan, for all your hard work on this! Here are a few things I think we can tweak.

Review:
- The intro starts too quickly, can we add a 2 second pause at the start.
- I would like to re-record the intro to match the thumbnail. - 'to save and export design variations'
- 0:35 Add a static image of a theme, such as https://wordpress.org/themes/twentytwentyfour/, when we say, "Once you have installed and activated a theme on your website."
- Then we can have the changing image when we say: _"you might want to make some changes, such as adjusting colors and layouts to match your brand or personal preferences. By default, these changes are stored as database entries—they are not integrated into the theme files."_ Please remove the heading _"How changes in the Site Editor work"_ as it is a bit distracting.  
- 0:54 - 1:06 Please remove the heading 'How changes in the Site Editor work' and make the arrow static - no movement. 
- 1:04. There is a typo. 'Blog' should be 'Block' &  'Create Block Theme' should also be in capital letters.
- 1:07- 1:17 Can we have a slide with only text for this portion _"It lets you transform your customizations into permanent variations of the original theme and export the modified theme as a .zip file, effectively creating your own custom theme."_
- 1:18 - 1:23 For the text _"You’ll then be able to use it in other WordPress sites without having to redesign the same elements."_ you can move back to the slide where you have the duplicate images on the left and right with the arrow in between; and Create Block Theme plugin at the top. You can remove the '.zip file' text. Again, no heading. Remove 'How changes in the Site Editor work.' 
- 1:24 - 1:30 Can we have a slide with only text for this portion _"This approach is particularly important because it avoids overwriting user customizations when updating the theme."_ 
- 1:31 - 1:35 Can we have a slide with only the backup graphic/element. 
- 2:00 - 2:09 Please add a pause before moving on to the next portion of text so that we finish drawing the back rectangle while still referring to _"Clone the active theme."_ The last rectangle should only be drawn once we say, _"Or create a child theme."_ There should therefore be a pause before "Or create a child theme". There should also be a pause before we say _"As mentioned..."_ The black rectangle should be gone before we say, "As mentioned."
- 5:07 Please draw a box around the content in lines 8 - 10 to highlight it.
- 5:12 - 5:20 I think I need to re-record this section as 'allowed' sounds strange.
- 6:03 Please change '2024' in two places to 'Twenty Twenty-Four.'
- 6:25 Please add a 2 - 3 pause at the end of the video as it ends a bit too abruptly.

**Comment by westnz** [comment] 2024-08-25 23:14
https://github.com/user-attachments/assets/7d467327-12f0-4b57-8219-78d6ff405976

**Comment by drussell17** [comment] 2024-08-26 16:47
Well done Wes.  The only thing that "bothered" me was that at the end when you advise that the theme will still have the name TT4, it begs the question w/r/t how best to save those variations as a theme with a different name.  Am I correct to assume that the clone option would not accomplish that result?  Bottom line is that I'd expect you do get that question once it's live and perhaps it could be addressed in the video.

**Comment by westnz** [comment] 2024-08-27 00:01
Thank you for the feedback @drussell17 👍

**Comment by westnz** [comment] 2024-08-28 04:33
Review:
1. At **1:09**, after chatting to a content creator, it was advised to have fewer slides with text. Can we keep the graphic with the two images and arrow + Create Block Theme plugin as is while we say, "It lets you transform your customizations into permanent variations of the original theme and export the modified theme as a .zip file, effectively creating your own custom theme?" It will then flow in nicely when the second image appears at **1:21**. And then, can we keep that last graphic in place when we say, "This approach is particularly important because it avoids overwriting user customizations when updating the theme." instead of the slide with text? Apologies, I know I asked for this before.

**Comment by helenaartmann** [comment] 2024-08-30 23:03
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [X] Learning outcomes/objectives are clear.
- [X] Technical concepts introduced in the content are accurate.
- [X] The speed of demonstrations is easy to follow.
- [X] The narration audio matches what is shown visually.
- [X] Spelling and grammar are correct.
- [X] Sound quality is consistent throughout the video.
- [X] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)). (How can I confirm this?)

I found this lesson easy to follow, with clear learning outcomes. I agree that the lesson ends abruptly, but this is my first time reviewing a lesson, so I am unsure if it should be like this.

**Comment by westnz** [comment] 2024-09-01 21:37
Thank you for reviewing, @helenaartmann

**Comment by BSICTVince** [comment] 2024-09-04 04:31
Gather any relevant links to Support, Docs, or related material

Description and Objectives finalized

Lesson created and announced to the team for review

[Lesson reviewed](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/#are-you-reviewing-content-before-it-is-published)

Lesson video submitted and published to WPTV

Lesson created on Learn.WordPress.org

Lesson video published to YouTube

Lesson on Learn.WordPress.org updated with YouTube video

Lesson published to Learn.WordPress.org

**Comment by BSICTVince** [comment] 2024-09-04 04:40
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.


The lessons and tutorials provided are excellent and informative. However, similar content can be found on platforms like Learn WordPress and WordPress TV. I want to suggest a new approach to these lessons. For example, we could start with a mockup created in Figma and then demonstrate how to design and develop that theme from Figma to WordPress. While this approach may seem like "spoon-feeding," it appears effective, especially for new and aspiring theme and template developers.

**Comment by westnz** [comment] 2024-09-04 23:45
Thanks for the feedback @BSICTVince. That is something we could consider for the Designer learning pathway.

**Comment by digitalchild** [comment] 2024-09-05 10:51
Great lesson, my only feedback is the same as the others with the abrupt ending. 

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by kathrynwp** [comment] 2024-09-09 17:52
Heya @westnz - here are a couple more thoughts:

4:55 - when you mention theme.json, the learner may not know what you’re referring to as it wasn’t mentioned before. Suggest either explaining it a little, or rewording in a different way to omit the reference.

After making changes to the theme, wouldn’t it be quite important to **change the name of the theme** (and the slug) before exporting it? Doesn’t keeping the same name mean that the changes you previously made will be overwritten on the the next theme update, which negates one of the reasons for having exported it as a new theme in the first place?

**Comment by westnz** [comment] 2024-09-09 20:51
Thank you for the feedback @digitalchild and @kathrynwp

**Comment by ervanyuff** [comment] 2024-09-10 08:20
Hi team, thanks for all the feedback. Here's [the updated video](https://drive.google.com/file/d/10X1wQQ4ulVcIcANj9G3HX2wROHHCOm6D/view?usp=sharing) 🙏

**Comment by kathrynwp** [comment] 2024-09-10 20:30
Great updates! The clarifications about `theme.json` are helpful, and adding the step where you export as a blank theme and rename it at the same time is perfect.

**Comment by westnz** [comment] 2024-09-10 20:41
Thanks, everyone!  I will publish it later today or tomorrow! 

Appreciate your work on this @ervanyuff

**Comment by westnz** [comment] 2024-09-11 08:35
//published

**Closed as completed** 2024-09-11 08:35 UTC
Labels: [Content] Published
